apiVersion: apps/v1
kind: Deployment
metadata: 
  name: hive 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hive
  template:
    metadata:
      labels:
        app: hive 
    spec:
      containers:
        - name: hive
          image: ghcr.io/abecker7/hivebox/abecker7/hive-docker:0.6.4 # {"$imagepolicy": "flux-system:hive"}
          imagePullPolicy: IfNotPresent
          ports: 
            - name: hive 
              containerPort: 5050 
              hostPort: 5050
              protocol: TCP
