apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hive-ingress
spec:
  defaultBackend:
    services:
      name: hive-service
      port:
        number: 80
  rules:
  - http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          services:
            name: hive-service
            port:
              number: 80
