apiVersion: "v1"
kind: "Service"
metadata:
  name: "hive-service"
  namespace: "production"
  labels:
    kustomize.toolkit.fluxcd.io/name: "production"
    kustomize.toolkit.fluxcd.io/namespace: "flux-system"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5050
  selector:
    app: "hive"
  type: "LoadBalancer"
  loadBalancerIP: ""

